### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by rex4539** [adityapk00/zecwallet-lite#44]
rustc 1.43.0-nightly (45ebd5808 2020-03-15)
node v12.16.1

```
   Compiling async-trait v0.1.24
error: failed to run custom build command for `neon-sys v0.3.3`

Caused by:
  process didn't exit successfully: `/Users/rex/zecwallet-lite/native/target/release/build/neon-sys-223278174df3d4d0/build-script-build` (exit code: 1)
--- stdout
Skipping node-gyp installation as part of npm install.
added 96 packages from 70 contributors and audited 184 packages in 8.553s
found 4 vulnerabilities (1 moderate, 3 high)
  run `npm audit fix` to fix them, or `npm audit` for details

> @ build-release /Users/rex/zecwallet-lite/native/target/release/build/neon-sys-4f9d4bb3d9a15f21/out/native
> node-gyp build

  CXX(target) Debug/obj.target/neon/src/neon.o
  SOLINK_MODULE(target) Debug/neon.node
TARGET = Some("x86_64-apple-darwin")
HOST = Some("x86_64-apple-darwin")
AR_x86_64-apple-darwin = None
AR_x86_64_apple_darwin = None
HOST_AR = None
AR = None
running: "ar" "crs" "/Users/rex/zecwallet-lite/native/target/release/build/neon-sys-4f9d4bb3d9a15f21/out/libneon.a" "/Users/rex/zecwallet-lite/native/target/release/build/neon-sys-4f9d4bb3d9a15f21/out/native/build/Release/obj.target/neon/src/neon.o"
cargo:warning=ar: /Users/rex/zecwallet-lite/native/target/release/build/neon-sys-4f9d4bb3d9a15f21/out/native/build/Release/obj.target/neon/src/neon.o: No such file or directory
exit code: 1

--- stderr
npm WARN lifecycle The node binary used for scripts is /var/folders/pn/rswd5k6175d02hbt25tvl47r0000gn/T/yarn--1584328853050-0.19841034227711285/node but npm is using /usr/local/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
In file included from ../src/neon.cc:8:
../src/neon_string.h:28:5: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
    maybe.ToLocal(&result);
    ^~~~~~~~~~~~~ ~~~~~~~
In file included from ../src/neon.cc:10:
../src/neon_task.h:62:11: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    node::MakeCallback(isolate_, context->Global(), callback, 2, argv);
          ^
/Users/rex/.electron-gyp/7.1.4/include/node/node.h:174:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/rex/.electron-gyp/7.1.4/include/node/node.h:93:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
2 warnings generated.


error occurred: Command "ar" "crs" "/Users/rex/zecwallet-lite/native/target/release/build/neon-sys-4f9d4bb3d9a15f21/out/libneon.a" "/Users/rex/zecwallet-lite/native/target/release/build/neon-sys-4f9d4bb3d9a15f21/out/native/build/Release/obj.target/neon/src/neon.o" with args "ar" did not execute successfully (status code exit code: 1).



warning: build failed, waiting for other jobs to finish...
error: build failed
neon ERR! cargo build failed

Error: cargo build failed
    at Target.<anonymous> (/Users/rex/zecwallet-lite/node_modules/neon-cli/lib/target.js:121:35)
    at step (/Users/rex/zecwallet-lite/node_modules/neon-cli/lib/target.js:32:23)
    at Object.next (/Users/rex/zecwallet-lite/node_modules/neon-cli/lib/target.js:13:53)
    at fulfilled (/Users/rex/zecwallet-lite/node_modules/neon-cli/lib/target.js:4:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
electron-build-env error
error Command failed with exit code 1.
```

**Comment by rex4539** [comment]
Was caused by bad node.js installation.

Fixed by a clean install of node v13.11.0
