### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by rex4539** [adityapk00/zecwallet-lite#72]
rustc 1.49.0-nightly (adef9da30 2020-10-13)

```
 Compiling bellman v0.6.0 (https://github.com/adityapk00/librustzcash.git?rev=ff0ffc3d1b8bc36a0ad4b6b0f06aa3ca5900d3e4#ff0ffc3d)
error[E0277]: cannot multiply-assign `&&<E as ScalarEngine>::Fr` to `<E as ScalarEngine>::Fr`
   --> /Users/rex/.cargo/git/checkouts/librustzcash-86501589fcbb0833/ff0ffc3/bellman/src/gadgets/test/mod.rs:131:24
    |
131 |         tmp.mul_assign(&coeff);
    |                        ^^^^^^ no implementation for `<E as ScalarEngine>::Fr *= &&<E as ScalarEngine>::Fr`
    |
    = help: the trait `MulAssign<&&<E as ScalarEngine>::Fr>` is not implemented for `<E as ScalarEngine>::Fr`
help: consider further restricting the associated type
    |
122 | ) -> E::Fr where <E as ScalarEngine>::Fr: MulAssign<&&<E as ScalarEngine>::Fr> {
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0277]: cannot multiply-assign `&&<E as ScalarEngine>::Fr` to `<E as ScalarEngine>::Fr`
   --> /Users/rex/.cargo/git/checkouts/librustzcash-86501589fcbb0833/ff0ffc3/bellman/src/groth16/generator.rs:389:39
    |
389 |                         at.mul_assign(&beta);
    |                                       ^^^^^ no implementation for `<E as ScalarEngine>::Fr *= &&<E as ScalarEngine>::Fr`
    |
    = help: the trait `MulAssign<&&<E as ScalarEngine>::Fr>` is not implemented for `<E as ScalarEngine>::Fr`
help: consider further restricting the associated type
    |
324 |     ) where <E as ScalarEngine>::Fr: MulAssign<&&<E as ScalarEngine>::Fr> {
    |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0277]: cannot multiply-assign `&&<E as ScalarEngine>::Fr` to `<E as ScalarEngine>::Fr`
   --> /Users/rex/.cargo/git/checkouts/librustzcash-86501589fcbb0833/ff0ffc3/bellman/src/groth16/generator.rs:390:39
    |
390 |                         bt.mul_assign(&alpha);
    |                                       ^^^^^^ no implementation for `<E as ScalarEngine>::Fr *= &&<E as ScalarEngine>::Fr`
    |
    = help: the trait `MulAssign<&&<E as ScalarEngine>::Fr>` is not implemented for `<E as ScalarEngine>::Fr`
help: consider further restricting the associated type
    |
324 |     ) where <E as ScalarEngine>::Fr: MulAssign<&&<E as ScalarEngine>::Fr> {
    |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0277`.
error: could not compile `bellman`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
neon ERR! cargo build failed

Error: cargo build failed
    at Target.<anonymous> (/Users/rex/zecwallet-lite/node_modules/neon-cli/lib/target.js:121:35)
    at step (/Users/rex/zecwallet-lite/node_modules/neon-cli/lib/target.js:32:23)
    at Object.next (/Users/rex/zecwallet-lite/node_modules/neon-cli/lib/target.js:13:53)
    at fulfilled (/Users/rex/zecwallet-lite/node_modules/neon-cli/lib/target.js:4:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
electron-build-env error
error Command failed with exit code 1.
```

**Comment by adityapk00** [comment]
Hmm.. Looks like a problem with the nightly compiler. I'll look into it

**Comment by adityapk00** [comment]
Tracking in #88, so closing this. 

Also see upstream issue: https://github.com/zcash/librustzcash/issues/333
